[package]
name = "rstow"
version = "1.0.1"
authors = ["qboileau <quentin.boileau@gmail.com>"]

[dependencies]
quicli = "0.3"
im = "11.0.1"
failure = "0.1.2"
failure_derive = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5.3"
